const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawn } = require('child_process');
const port = 17378;
const dataDir = fs.mkdtempSync(path.join(os.tmpdir(), 'tona-builtin-skills-'));
const child = spawn(process.execPath, ['server.js'], { cwd: path.resolve(__dirname, '..'), env: { ...process.env, PORT: String(port), DATA_DIR: dataDir }, stdio: ['ignore', 'pipe', 'pipe'] });
async function request(url, options={}) { const response = await fetch('http://127.0.0.1:' + port + url, { ...options, headers: { 'Content-Type':'application/json', ...(options.headers||{}) } }); const body=await response.json(); if(!response.ok)throw new Error(response.status+': '+JSON.stringify(body)); return body; }
async function ready(){for(let i=0;i<40;i+=1){try{return await request('/api/state');}catch{await new Promise((r)=>setTimeout(r,80));}}throw new Error('Server did not start');}
(async()=>{try{const state=await ready(); const ids=new Set(state.workflows.map((item)=>item.id)); for(const id of ['skill_creator','skill_test','feishu_learning','research_brief','meeting_assistant','daily_report','copywriting_designer','document_review','multi_agent_review']) if(!ids.has(id))throw new Error('Missing built-in skill: '+id); const draft=await request('/api/skills/draft',{method:'POST',body:JSON.stringify({request:'\\u628a\\u6bcf\\u5468\\u7814\\u7a76\\u9605\\u8bfb\\u505a\\u6210\\u7b80\\u62a5'})}); if(!draft.skill?.name || !draft.skill.steps?.length)throw new Error('Draft skill was not created'); const afterDraft=await request('/api/state'); if(afterDraft.workflows.length!==state.workflows.length)throw new Error('Draft unexpectedly wrote to Skill Center'); const run=await request('/api/skills/test',{method:'POST',body:JSON.stringify({skillId:'meeting_assistant',input:'\\u65f6\\u95f4\\uff1a\\u660e\\u5929\\u4e0a\\u534810\\u70b9\\uff1b\\u76ee\\u6807\\uff1a\\u8ba8\\u8bba\\u7814\\u7a76\\u8ba1\\u5212'})}); if(!run.testOnly || !run.finalOutput)throw new Error('Skill test did not return a sandbox result'); console.log('Built-in Skill test passed: templates, draft-only generation, and Studio-only test run.');}finally{child.kill();fs.rmSync(dataDir,{recursive:true,force:true});}})().catch((error)=>{console.error(error);process.exitCode=1;});
